### ISSUE TITLE
actualBalance() should only include accepted Transactions

### ISSUE THREAD

**Issue by chadtomkiss** [depsimon/laravel-wallet#1]
**Issue:**

When using the `actualBalance()` method in `HasWallet`, the amount doesn't match `balance` field on the `wallets` table as it includes transactions that weren't `accepted`

Should there be a `where('accepted', 1)` added to the query builder?

**Comment by depsimon** [comment]
Yeah it seems to be the case. Would you care to do a PR to fix this?
