### ISSUE TITLE
transactions() relation includes transactions that are not accepted

### ISSUE THREAD

**Issue by chadtomkiss** [depsimon/laravel-wallet#2]
Should `$user->transactions()` default to only include transactions that are `accepted`?

Similar to how Eloquent filters out soft deleted models, but you can use the `withTrashed()` to include ones that are deleted.

Maybe `$user->transactions()->withRejected()->get()` if you wanted every transaction or something?

**Comment by depsimon** [comment]
In all of my current use cases I'm always showing the list of all transactions. It's important for the clients & the admins to see the failed transactions as well otherwise it could confuse them.

**Comment by chadtomkiss** [comment]
That's cool.

I added a method to calculate a running balance next to each transaction, which is wrong due to including failed transactions but I will add a where clause to the transactions I am getting :+1:
