### ISSUE TITLE
will race condition happen ?

### ISSUE THREAD

**Issue by rained23** [depsimon/laravel-wallet#5]
Hi,

Can I know if I use the deposit or withdraw function is that possible race condition happen ?
let say a malicious user try to invoke withdraw function simultaneously, the wallet have balance of 10 and withdrawn 10 simultaneously , can both withdraw success ?

**Comment by depsimon** [comment]
I'm not sure. I guess it'd be possible but I haven't wrote any tests yet to check this kind of things.

**Comment by ademakanaky** [comment]
Before withdrawals, you can always check if user->canWithdraw($amount); This way you guide against race conditions.

**Comment by rained23** [comment]
This is an old question, to be safe, run anything like this with a transaction, doing check will still be affected by 
both clients reading on the same record.
